# File for creating a container of this testsuite.
FROM registry.access.redhat.com/ubi8/openjdk-8:latest
USER root
RUN whoami

# Install required utilities
RUN microdnf -y install util-linux

# Create the directory structure for the testing.
RUN mkdir -p /tmp/rhscl_openshift_dir/openjdk
WORKDIR /tmp/rhscl_openshift_dir/openjdk
COPY . .

# Update the permissions on the testsuite
RUN chgrp -R 0 /tmp/rhscl_openshift_dir/openjdk && \
    chmod -R g=u /tmp/rhscl_openshift_dir/openjdk && \
    chgrp -R 0 /home && \
    chmod -R g=u /home